export const topic = 'AI 投资热潮：生产率革命，还是资本错配？';
export const thinkers = [
{id:'bernanke',initials:'BB',name:'Ben Bernanke',cn:'伯南克',field:'信用与金融加速器',mechanism:'资产负债表恶化可能提高外部融资成本，进而放大投资与经济波动。',question:'如果估值回落，谁的融资链条会先断裂？',boundary:'不能把股价下跌直接等同于银行危机；需要检查杠杆、抵押品和融资期限。',source:'https://www.nobelprize.org/prizes/economic-sciences/2022/bernanke/lecture/'},
{id:'mundell',initials:'RM',name:'Robert Mundell',cn:'蒙代尔',field:'开放经济与资本流动',mechanism:'资本流动、汇率制度和货币政策相互约束，政策效果依赖开放经济条件。',question:'资本流向哪里？汇率和跨境融资成本如何改变投资回报？',boundary:'必须说明汇率制度与资本流动条件，不能把一个经济体的结论直接推广到全球。',source:'https://www.nobelprize.org/uploads/2018/06/mundell-lecture.pdf'},
{id:'aghion',initials:'PA',name:'Philippe Aghion',cn:'阿吉翁',field:'创新与创造性破坏',mechanism:'新技术替代旧技术，竞争、进入与退出机制影响创新激励和长期增长。',question:'资金在支持新进入者，还是巩固既有企业的壁垒？',boundary:'创造性破坏不等于支持无差别倒闭；需要考虑竞争结构和转型成本。',source:'https://www.nobelprize.org/uploads/2025/12/lecture-aghion.pdf'},
{id:'shiller',initials:'SH',name:'Robert Shiller',cn:'席勒',field:'叙事与资产定价',mechanism:'投资者预期、社会传播与价格反馈可能使估值偏离基本面。',question:'乐观叙事何时能够被现金流验证？',boundary:'估值偏高不能给出泡沫破裂的精确时间，也不能否认真实技术进步。',source:'https://www.nobelprize.org/prizes/economic-sciences/2013/shiller/lecture/'},
{id:'solow',initials:'SO',name:'Robert Solow',cn:'索洛',field:'资本深化与生产率',mechanism:'增长核算区分资本、劳动投入与生产率，资本增加本身不能保证持续的效率提升。',question:'控制资本和劳动投入后，额外产出还剩多少？',boundary:'生产率残差不是纯粹的技术进步，也会受测量、利用率和结构变化影响。',source:'https://www.nobelprize.org/prizes/economic-sciences/1987/solow/lecture/'}
];
export const sources=[{title:'增长核算：资本 ≠ 生产率',author:'Robert Solow · 1987 Nobel Lecture',url:thinkers[4].source,note:'用于区分投入增加与效率提升。本文献不提供本期 AI 产业的实时数据。'}, {title:'信用如何放大经济波动',author:'Ben Bernanke · 2022 Nobel Lecture',url:thinkers[0].source,note:'用于理解信贷与资产负债表的反馈机制。是否适用于 AI 投资需要融资结构证据。'}, {title:'创新与创造性破坏',author:'Philippe Aghion · Nobel Lecture',url:thinkers[2].source,note:'用于讨论进入、退出与创新激励；不是对当前 AI 公司投资价值的判断。'}];
export const candidates=[{id:'ai-growth',tag:'技术与增长',title:topic,description:'资本开支、创新扩散与市场叙事，谁先被现实验证？'}, {id:'credit-transition',tag:'货币与金融',title:'降低利率，能否真正修复企业投资意愿？',description:'当需求不足与资产负债表约束并存，货币政策如何传导？'}, {id:'global-fragmentation',tag:'全球经济',title:'产业链回流：提升韧性，还是牺牲效率？',description:'重新审视贸易分工、政策成本与供应安全的边界。'}];
export type Turn={speaker:string;text:string;kind?:string};
export const rounds:Turn[][]=[
[{speaker:'bernanke',text:'我的起点是融资结构，而非技术是否令人兴奋。如果项目依赖短期债务，预期回报的小幅下修就可能经由抵押品与信贷条件放大。若主要由股权和经营现金流融资，股价回调未必演变为信用危机。需要核验：债务期限、融资集中度和现金流覆盖。',kind:'独立判断'}, {speaker:'mundell',text:'资本错配不能只在单一国家内部判断。跨境资本可能追逐不同地区的税收、利率与算力成本；汇率变化又会重估回报。在讨论政策效果前，应先区分本币融资与外币融资、固定与浮动汇率条件。',kind:'独立判断'}, {speaker:'aghion',text:'我关心投资是否打开了创新入口。基础设施投入可能帮助新企业进入，也可能被少数企业用于建立壁垒。创新不是资本开支的同义词。如果新企业能以更低成本推出有效应用，乐观判断会更有依据。',kind:'独立判断'}, {speaker:'shiller',text:'技术确实进步与资产被过度定价，可以同时成立。一个易传播的未来故事，可能让投资者忽略兑现周期。我会把估值所隐含的增长预期，与实际可观察的付费需求和现金流放在一起检验，而不预测拐点日期。',kind:'独立判断'}, {speaker:'solow',text:'购置更多设备首先意味着资本深化。要论证生产率革命，必须观察单位投入的产出变化，并处理采用时滞、产能利用率与测量误差。短期未见宏观生产率改善，不足以否定技术；投入增加也不足以证明技术收益已兑现。',kind:'独立判断'}],
[{speaker:'host',text:'第一轮形成了两个不同层次的问题：社会能否获得生产率收益，以及投资者能否获得合理回报。现在请直接质询另一种框架的关键假设。',kind:'主持人梳理'}, {speaker:'aghion',text:'我想质询伯南克框架：如果为了防止信用收缩而持续保护既有投资，会不会阻止低效率项目退出？金融稳定措施应保护融资机制，不应自动保护每一家企业。检验标准是：新的、更有效率的企业是否仍能进入。',kind:'质询 · 伯南克框架'}, {speaker:'bernanke',text:'阿吉翁提出了重要边界。个别企业退出与融资中介失灵是两回事。我的担忧不是让所有项目继续，而是一个项目的失败是否切断了其他有价值项目的融资。需要比较损失承担结构，而非只看退出数量。',kind:'回应 · 阿吉翁框架'}, {speaker:'shiller',text:'我想补充索洛框架的时间差：市场可能在生产率兑现前就计入了过多成功。即使未来技术有用，买入价格也可能过高。因此，宏观生产率改善不能单独证明今天的资产定价合理。',kind:'质询 · 索洛框架'}],
[{speaker:'host',text:'引入一组明确的假设情景，而非实时新闻：假设应用收入增长，但融资利差同时扩大、设备利用率下降。请说明什么改变了，什么尚未改变。',kind:'假设情景 · 非实际数据'}, {speaker:'solow',text:'收入增长提供需求线索，但利用率下降使产出和资本存量的关系更难解读。我会降低“资本已普遍转化为生产率”的判断权重，继续核验同口径单位投入产出。收入增长也可能来自价格变化，不能直接当作实际产出增长。',kind:'条件更新'}, {speaker:'bernanke',text:'利差扩大提高了融资脆弱性的关注度，但还要判断它反映预期违约、流动性还是普遍利率变化。如果现金流覆盖仍充足，风险判断不应机械上调到系统危机。',kind:'条件更新'}, {speaker:'aghion',text:'设备利用率下降既可能是重复建设，也可能是新技术替代旧设备。若新进入者的采用成本下降、有效应用扩散，我仍保留长期创新潜力的判断；同时降低对所有既有投资都能回本的预期。',kind:'条件更新'}, {speaker:'host',text:'本期共识：技术进步、生产率兑现和投资回报需要分别验证。最大分歧：在收益尚未显现时，应给予扩张多少耐心。下一步核验五项数据：单位投入产出、付费留存、自由现金流、融资期限与信用利差、产能利用率及新企业进入。以上为教学演示推演，不是对现实市场的已验证结论。',kind:'共识与分歧'}]
];
